config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms do
    resource :room_users
    resources :chatmessages
  end

  resources :private_chats
  root   'chatrooms#index'

  devise_for :users
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
   scope :get_private_chatrooms, ->{where(private_chat: true) }
   scope :get_public_chatrooms, ->{where(private_chat: false) }

   has_many :room_users, dependent: :destroy
   has_many :users, through: :room_users
   has_many :roommessages, dependent: :destroy

end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  before_create :set_last_read_at

  belongs_to :chatroom
  belongs_to :user

  def set_last_read_at
    self.last_read_at = self.created_at
  end
end

app/models/roommessage.rb
class Roommessage < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :get_user_name

  has_many :room_users
  has_many :chatrooms, through: :room_users
  has_many :roommessages

  def get_user_name
      @emailarray = Array.new
      @emailarray = self.email.split("@")
      self.username = @emailarray[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chatmessage_controller.rb
class ChatmessageController < ApplicationController
  before_action :authenticate_user!, :only => [:index, :update, :join]

  def index
  end

  def show
  end

  def join
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom

  end

  def update
  end

  def distroy
  end
end

app/controllers/chatmessages_controller.rb
class ChatmessagesController < ApplicationController
  before_action :authenticate_user!, :only => [:index, :update, :join, :edit]

  def join
    @chatroom_user = @chatroom.room_users.where(user_id: current_user.id,
                                                private_chat:false
                                                ).first_or_create
    redirect_to @chatroom
  end

  def new
    p params
    @chatroomid = params[:chatroom_id]
    @message = params[:body]
    @roommsg = Roommessage.create!(chatroom_id: @chatroomid, user_id: current_user.id, body: @message)

    if @roommsg
        Chatroom.find(@chatroomid).update!(updated_at:Time.zone.now)
        @chatroom=Chatroom.find(@chatroomid)
        ActionCable.server.broadcast(
                                    'room_channel',
                                    roomid: @chatroomid,
                                    roomname:@chatroom.roomname,
                                    private_chat:@chatroom.private_chat,
                                    username: current_user.username,
                                    userid: current_user.id,
                                    message: @message,
                                    created_at:Time.zone.now.to_s
                                    )
    end
    redirect_to  chatroom_path(id:@chatroomid )
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chatrooms = Chatroom.where(private_chat: false)
  end

  def create
    @chatroom = Chatroom.create(roomname: params.require(:chatroom)[:roomname], create_user: current_user.id)
    if @chatroom
       RoomUser.create(chatroom_id: @chatroom.id,
                       user_id: current_user.id,
                       last_read_at: Time.zone.now
                      )
       redirect_to "/"
    end
  end

  def new
    @chatroom = Chatroom.new
  end

  def edit
    if !Chatroom.find(params[:id]).private_chat
       RoomUser.create(
                       chatroom_id:params[:id],
                       user_id:current_user.id,
                       last_read_at:Time.zone.now
                      )
    end
    redirect_to "/"
  end


  def show
    @chatroomid = params[:id]
    @chatroom = Chatroom.find(@chatroomid)
    if @chatroom

       @chatmeaaage = Chatroom.find(@chatroomid).roommessages.order(created_at: :desc).limit(10).reverse

       current_user.room_users.where(chatroom_id: @chatroomid).update(last_read_at: Time.zone.now)

       render "/chatrooms/show"
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
     @chatrooms=Chatroom.get_private_chatrooms
  end
end

app/controllers/private_chats_controller.rb
class PrivateChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @chatroom = if_private_chat_or_not
    params[:id] = @chatroom.id
    @chatmeaaage = Chatroom.find(@chatroom.id).roommessages.order(created_at: :desc).limit(10).reverse
    current_user.room_users.where(chatroom_id: @chatroomid).update(last_read_at: Time.zone.now)
    @chatroom_user = current_user.room_users.find_by(chatroom_id: @chatroom.id)
    render "/chatrooms/show"
  end

  def if_private_chat_or_not
    @to_user = User.find(params[:id])
    users = [current_user, @to_user]
    user_ids = users.map(&:id).sort
    @chatroomname = "#{user_ids.join("/")}"

    if @chatroom = Chatroom.get_private_chatrooms.where(roomname: @chatroomname).first
       @chatroom
    else
       # create a new chatroom
       @chatroom = Chatroom.create!(roomname: @chatroomname,
                                    create_user:current_user.id,
                                    private_chat: true
                                    )
       @chatroom.room_users.where(user_id: current_user.id).first_or_create
       @chatroom.room_users.where(user_id: @to_user.id).first_or_create
       @chatroom
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chatmessages_helper.rb
module ChatmessagesHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
  # 通过邮件地址获取客户的用户名
  def getusername(email)
      @emailarray[] = email.split("@")
      @emailarray[0]
  end
end

app/helpers/private_chats_helper.rb
module PrivateChatsHelper
end

app/views/chat/index.html.erb
<% provide(:title, "Danile") %>
<p id="notice"><%= notice %></p>
<h1>Chatrooms</h1>
  <body>
  <table>
  <% @chatrooms.each do |chatroom| %>
        <tr>
          <td><%= chatroom.roomname %></td>
          <td><%= link_to "Join", chatmessage_join_path, method: :post %></td>
        </tr>
    <% end %>
  </table>
  </body>

<br>

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
    <% if chatroom.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>
          <ul>
            <% chatroom.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :roomname %>
      <%= f.text_field :roomname %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/chatrooms/index.html.erb
<% provide(:title, "Home") %>
<h1>Other rooms</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% (@chatrooms-current_user.chatrooms).each do |chatroom| %>
      <tr>
        <td><%= chatroom.roomname %></td>
        <td><%= link_to "Join", edit_chatroom_path(chatroom.id) %></td>
      </tr>

  <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Create Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<% provide(:title, "New chatrooms") %>
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom%>

<%= link_to 'Back', root_path %>

app/views/chatrooms/show.html.erb
<% provide(:title, @chatroom.roomname) %>
<p>
<h2><strong><%= (@chatroom.private_chat) ? ("chat with friend") : ("chatroom: "+@chatroom.roomname) %></strong></h2>

</p>


<div id="chatmessages" style="height: 400px;width:600px;overflow: scroll">
  <% @chatmeaaage.each do |message| %>
      <h5> <%=message.created_at.to_s+"  "+User.find(message.user_id).username + " say "  %><br></h5>
      <span><h4><%=message.body%><h4></span>
  <% end %>
</div>

<form id="send_msg" action=<%=new_chatroom_chatmessage_path(chatroom_id: @chatroom.id) %>>
  <div>
    <textarea id="body" class="form-control" placeholder="Your reply here..."  rows="3"  name="body"></textarea>
    <input id="user_id" name="user_id"  value=<%=current_user.id %>  type="hidden"/>
    <input id="room_id" name="room_id"  value=<%=@chatroom.id %>  type="hidden"/>
  </div>
  <div>
    <button class="btn btn-primary" type="submit" id="submit">Reply</button>
  </div>
</form>

app/views/chats/index.html.erb
<% provide(:title, "Danile") %>
<p id="notice"><%= notice %></p>
<h1>Chatrooms</h1>
  <body>
  <table>
  <% @chatrooms.each do |chatroom| %>
        <tr>
          <td><%= chatroom.roomname %></td>
          <td><%= link_to "Join", chatmessage_join_path, method: :post %></td>
        </tr>
    <% end %>
  </table>
  </body>
 <%= link_to 'New Chatroom', chatmessage_join_path, method: :post %>
<br>

app/views/layouts/_fooder.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to root_path, class: "navbar-brand" do %>
          Home
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <%= yield :right_nav %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Loginout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<div class="container">
  <span><%= link_to 'Join a Chatroom', root_path %></span>
  <div style="float: right">
    <% if user_signed_in? %>
    <span style="color: red"> <%= current_user.username %></span>
        <%= link_to "Loginout", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<thead>
  <title><%= yield(:title) %> | Strikingly</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/header' %>
</thead>
<body>
<div id="chatrooms">
      <% if user_signed_in? %>
          <h4>My chatrooms</h4>
          <ul>
            <% current_user.chatrooms.get_public_chatrooms.each do |chatroom| %>
                <li>
                <a href="#" class="media active-message">
                  <div class="media-body">
                  <img id="<%=chatroom.id%>" class="d-flex mr-3" src=<%= (chatroom.updated_at) < (RoomUser.where(chatroom_id:chatroom.id,user_id:current_user.id).last.last_read_at)? "https://robohash.org/4.png?set=set3": "https://robohash.org/4.png?set=set4"
                  %> width="25" /><strong><%= link_to chatroom.roomname, chatroom, data: { chatroom_id: chatroom.id} %></strong><br/>
                  </div>
                </a>
                </li>
            <% end %>
          </ul>


      </div>
      <div id="users">
          <h4>Private friends</h4>
          <ul>
            <% current_user.chatrooms.get_private_chatrooms.each do |privatechat| %>
                <li>
                  <a href="#" class="media active-message">
                    <div class="media-body">
                      <img id="<%=privatechat.id%>" class="d-flex mr-3" src="https://robohash.org/4.png?set=set3" width="25" /><strong><%= link_to privatechat.roomname, privatechat%></strong><br/>
                    </div>
                  </a>
                </li>
            <% end %>
          </ul>
      <% end %>
    </div>
<div class="col-sm-10 col-sm-offset-2" style="position: fixed; top: 40px; left: 450px;">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application_demp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Strikingly</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/header' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>